### ISSUE TITLE
Dragon Rise USB Joystick lefty inverted with rightx.

### ISSUE THREAD

**Issue by panzergame** [gabomdq/SDL_GameControllerDB#86] opened 2016-06-24 10:30 UTC
Recently for a patch in a project about joystick is noticed that the mapping for `DragonRise Inc.   Generic   USB  Joystick` was wrong on some axis. The left Y was inverted with the right X.

I regenerated the mapping an now i have:

```
03000000790000000600000010010000,DragonRise Inc.   Generic   USB  Joystick  ,x:b3,a:b2,b:b1,y:b0,back:b8,start:b9,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,dpup:h0.1,leftshoulder:b4,lefttrigger:b6,rightshoulder:b5,righttrigger:b7,leftstick:b10,rightstick:b11,leftx:a0,lefty:a3,rightx:a1,righty:a4
```

We can notice that it was before: `lefty:a1,rightx:a3`.

Could someone test if i'm right or it's something with kernel module or system ? Thanks in advance.

**Comment by panzergame** [comment] 2016-08-09 15:23
Can someone confirme my results ?

**Comment by DanielGibson** [comment] 2016-10-27 17:51
I can confirm this and your regenerated mapping works for me.
(I've got two "Trust CTX 24" which identify as "DragonRise Inc.   Generic   USB  Joystick" and have the given GUID)

**Comment by panzergame** [comment] 2016-10-28 08:49
Thank you.

**Comment by gabomdq** [comment] 2017-01-02 17:47
Merged, thanks!

**Closed by gabomdq** 2017-01-02 17:47 UTC
