### ISSUE TITLE
mapping for Mayflash Wii Classic Controller

### ISSUE THREAD

**Issue by DemonBigj781** [gabomdq/SDL_GameControllerDB#710] opened 2023-10-05 19:54 UTC
2509e803000000000000504944564944,Mayflash Wii Classic Controller,platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b8,start:b9,guide:b10,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

**Comment by offalynne** [comment] 2023-10-05 20:33
This is a duplicate of https://github.com/gabomdq/SDL_GameControllerDB/blob/55f1a1509f8f4a663c826ac8a572136ecfc13b53/gamecontrollerdb.txt#L402

**Closed by offalynne** 2023-10-05 20:33 UTC

**Comment by DemonBigj781** [comment] 2023-10-05 21:09
however it was faulty

**Comment by DemonBigj781** [comment] 2023-10-05 21:09
reference here
https://github.com/AntiMicroX/antimicrox/issues/843#issuecomment-1749565136
